#!/usr/bin/env python3
"""Verify that the committed font subsets really carry their declared text.

The browser-facing guard proves that served text belongs to CHARSET. This is
the reverse direction: every character in CHARSET must be assigned to a face
by fonts.css and mapped to a non-.notdef glyph by that committed WOFF2 file.
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    from fontTools.ttLib import TTFont
except ImportError as exc:  # pragma: no cover - environment setup failure
    raise SystemExit(
        "fontTools is required; install scripts/font-requirements.txt"
    ) from exc


ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "src" / "lib" / "fonts"


@dataclass(frozen=True)
class Face:
    path: Path
    ranges: tuple[tuple[int, int], ...]
    cmap: dict[int, str]

    def claims(self, codepoint: int) -> bool:
        return any(first <= codepoint <= last for first, last in self.ranges)

    def maps(self, codepoint: int) -> bool:
        return self.cmap.get(codepoint) not in (None, ".notdef")


def charset() -> str:
    source = (FONTS / "charset.ts").read_text(encoding="utf-8")
    match = re.fullmatch(
        r"// Generated by scripts/subset-fonts\.py - do not edit by hand\.\n"
        r"// The characters the font subsets carry\.\n"
        r"export const CHARSET = (.+);\n",
        source,
    )
    if not match:
        raise SystemExit("cannot read the generated CHARSET declaration")
    value = json.loads(match.group(1))
    if not isinstance(value, str) or not value:
        raise SystemExit("CHARSET must be a nonempty JSON string")
    if len(value) != len(set(value)):
        raise SystemExit("CHARSET contains duplicate characters")
    return value


def unicode_ranges(value: str) -> tuple[tuple[int, int], ...]:
    parsed: list[tuple[int, int]] = []
    for raw in value.split(","):
        token = raw.strip().upper()
        match = re.fullmatch(r"U\+([0-9A-F?]+)(?:-([0-9A-F]+))?", token)
        if not match:
            raise SystemExit(f"cannot parse unicode-range token {raw!r}")
        first_text = match.group(1)
        if "?" in first_text:
            if match.group(2):
                raise SystemExit(f"wildcard range may not have an upper bound: {raw!r}")
            first = int(first_text.replace("?", "0"), 16)
            last = int(first_text.replace("?", "F"), 16)
        else:
            first = int(first_text, 16)
            last = int(match.group(2), 16) if match.group(2) else first
        if first > last or last > 0x10FFFF:
            raise SystemExit(f"invalid unicode-range token {raw!r}")
        parsed.append((first, last))
    return tuple(parsed)


def faces() -> list[Face]:
    css = (FONTS / "fonts.css").read_text(encoding="utf-8")
    found: list[Face] = []
    for block in re.findall(r"@font-face\s*\{(.*?)\}", css, re.DOTALL):
        source = re.search(r"url\(['\"]?\./([^)'\"]+\.woff2)", block)
        ranges = re.search(r"unicode-range:\s*([^;]+);", block)
        if not source or not ranges:
            raise SystemExit("every generated @font-face needs a WOFF2 and unicode-range")
        path = FONTS / source.group(1)
        if not path.is_file():
            raise SystemExit(f"font face is missing: {path.name}")
        font = TTFont(path, lazy=False)
        try:
            cmap = font.getBestCmap() or {}
        finally:
            font.close()
        if not cmap:
            raise SystemExit(f"font face has no usable cmap: {path.name}")
        found.append(Face(path, unicode_ranges(ranges.group(1)), cmap))

    if not found:
        raise SystemExit("fonts.css declares no font faces")
    referenced = {face.path.name for face in found}
    committed = {path.name for path in FONTS.glob("*.woff2")}
    if referenced != committed:
        missing = sorted(committed - referenced)
        extra = sorted(referenced - committed)
        raise SystemExit(f"font/CSS file-set mismatch: unreferenced={missing}, missing={extra}")
    return found


def label(character: str) -> str:
    shown = character if not character.isspace() else repr(character)
    return f"{shown} (U+{ord(character):04X})"


def main() -> int:
    declared = charset()
    font_faces = faces()
    unassigned: list[str] = []
    missing: list[str] = []

    for character in declared:
        codepoint = ord(character)
        claimed = [face for face in font_faces if face.claims(codepoint)]
        if not claimed:
            unassigned.append(label(character))
        elif not any(face.maps(codepoint) for face in claimed):
            missing.append(
                f"{label(character)} claimed by "
                + ", ".join(sorted(face.path.name for face in claimed))
            )

    if unassigned or missing:
        if unassigned:
            print("declared characters outside every CSS range:", file=sys.stderr)
            print("\n".join(f"  {item}" for item in unassigned), file=sys.stderr)
        if missing:
            print("declared characters without a real glyph:", file=sys.stderr)
            print("\n".join(f"  {item}" for item in missing), file=sys.stderr)
        print("regenerate the subsets with scripts/subset-fonts.py", file=sys.stderr)
        return 1

    print(
        f"font subsets OK — declared={len(declared)} faces={len(font_faces)} "
        f"cmap-entries={sum(len(face.cmap) for face in font_faces)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
