#!/usr/bin/env python3
"""Cut the reading face down to the characters this edition actually sets.

EB Garamond ships every script it covers. A missal in Latin, Polish and
English renders 170 of those characters, and paying for the rest on every
page load is the largest single cost a reader carries: the stock latin-ext
file alone is 114 KB, of which this edition uses fourteen letters.

So the font files in src/lib/fonts are subsets, generated here from the
upstream package and committed like any other build product. The unicode
ranges, family name and weight axis are taken from upstream, so a page
still downloads only the ranges its text needs; each range is simply much
smaller. The variable weight axis is preserved.

Run it after a build (it reads the built pages to learn the characters),
from the app directory:

    python3 -m venv .venv && .venv/bin/pip install fonttools brotli
    npm run build && .venv/bin/python scripts/subset-fonts.py

The character set it derived is committed next to the fonts as a module
the test suite reads, and the suite fails if the served site ever needs a
character the subsets do not carry — that is the signal to run this again.
"""

from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

from fontTools import subset

APP = Path(__file__).resolve().parent.parent
BUILD = APP / "build"
UPSTREAM = APP / "node_modules" / "@fontsource-variable" / "eb-garamond"
OUT = APP / "src" / "lib" / "fonts"

# Scripts no page of this edition sets. Greek stays: the Kyrie's Greek and
# the etymologies in the lexicon are real text, and the ranges are small.
UNUSED = ("cyrillic", "cyrillic-ext", "vietnamese")

# A little room to move, so that adding one prayer does not mean
# regenerating the fonts: the letters of the three languages of this
# edition, whether or not a page happens to set them today.
MARGIN = (
    "".join(chr(c) for c in range(0x20, 0x7F))
    + "ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÑÒÓÔÕÖØÙÚÛÜÝ"
    + "àáâãäåæçèéêëìíîïñòóôõöøùúûüýÿ"
    + "ĀāĂăĆćĒēĖėĘęĪīĶķĹĺŁłŃńŌōŒœŚśŜŝŪūŸŹźŻżǢǣǼǽ"
    + "„“”‘’—–…·†‡§¶‹›«»×÷°"
)


def characters_in_build() -> set[str]:
    """Every character the built site can put on screen.

    Pages, scripts and stylesheets alike: text that only appears after
    hydration is text all the same, and a label the reader never sees in
    the HTML would otherwise fall back to a system face.
    """
    found: set[str] = set()
    for path in BUILD.rglob("*"):
        if path.suffix in (".html", ".js", ".css") and path.is_file():
            found.update(path.read_text(encoding="utf-8", errors="ignore"))
    return {c for c in found if ord(c) > 0x1F}


def faces() -> list[tuple[str, str, str]]:
    """(subset, style, unicode-range) for every face we keep, from upstream.

    Roman only, since 2026-08-21: the book sets no italic anywhere (the
    owner's ruling, recorded at the no-italics rule in app.css), so the
    italic faces would be 59 KB of dead weight in every cold load and in
    the offline copy. If an italic ever returns by design, restore the
    ("italic", "wght-italic.css") pair here and regenerate.
    """
    out = []
    for style, css in (("normal", "wght.css"),):
        text = (UPSTREAM / css).read_text(encoding="utf-8")
        for block in text.split("@font-face")[1:]:
            src = re.search(r"url\(\./files/eb-garamond-(.+?)-wght-", block)
            rng = re.search(r"unicode-range:\s*([^;]+);", block)
            if not src or not rng:
                raise SystemExit(f"cannot read {css}: upstream layout changed")
            if src.group(1) in UNUSED:
                continue
            unicode_range = rng.group(1).strip()
            # Ecclesiastical Latin needs a decomposed acute after œ in forms
            # such as fœ́deris. Google Fonts' upstream CSS omits U+0301 because
            # its usual Latin accents are precomposed, so assign the mark to
            # the Latin-ext face explicitly.
            if src.group(1) == "latin-ext":
                unicode_range += ",U+0301"
            out.append((src.group(1), style, unicode_range))
    return out


def main() -> None:
    if not BUILD.is_dir():
        raise SystemExit("no build/ — run `npm run build` first")

    charset = "".join(sorted(characters_in_build() | set(MARGIN)))
    OUT.mkdir(parents=True, exist_ok=True)
    # A module rather than a plain list, so the guard can read it without
    # reaching for the filesystem: the test suite has no Node typings and
    # checks what the server serves, not what sits in build/.
    (OUT / "charset.ts").write_text(
        "// Generated by scripts/subset-fonts.py - do not edit by hand.\n"
        "// The characters the font subsets carry.\n"
        f"export const CHARSET = {json.dumps(charset)};\n",
        encoding="utf-8",
    )

    kept = faces()
    css = [
        "/* Generated by scripts/subset-fonts.py — do not edit by hand.",
        " * EB Garamond, subset to the characters this edition sets.",
        " * Upstream ranges and weight axis preserved; see LICENSE. */",
        "",
    ]
    before = after = 0
    for name, style, unicode_range in kept:
        stem = f"eb-garamond-{name}-wght-{style}"
        source = UPSTREAM / "files" / f"{stem}.woff2"
        target = OUT / f"{stem}.woff2"
        subset.main(
            [
                str(source),
                f"--text={charset}",
                "--flavor=woff2",
                "--ignore-missing-unicodes",
                f"--output-file={target}",
            ]
        )
        before += source.stat().st_size
        after += target.stat().st_size
        print(f"  {stem:38} {source.stat().st_size / 1024:7.1f}K -> {target.stat().st_size / 1024:6.1f}K")
        css += [
            "@font-face {",
            "\tfont-family: 'EB Garamond Variable';",
            f"\tfont-style: {style};",
            "\tfont-display: swap;",
            "\tfont-weight: 400 800;",
            f"\tsrc: url('./{stem}.woff2') format('woff2-variations');",
            f"\tunicode-range: {unicode_range};",
            "}",
            "",
        ]

    (OUT / "fonts.css").write_text("\n".join(css), encoding="utf-8")
    shutil.copyfile(UPSTREAM / "LICENSE", OUT / "LICENSE")

    print(f"\n{len(charset)} characters, {len(kept)} faces: {before / 1024:.0f}K -> {after / 1024:.0f}K")


if __name__ == "__main__":
    main()
